### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by kurtkopchik** [comment]
Hi @fommil - Thanks for the PR!

The plugin supports being enabled on all or a subset of the projects and does not require that the `root` project support `dockerComposeUp`. For example, you can have a multi-project `build.sbt` file with 5 projects and you only want `dockerComposeUp` to be used from one of the sub-projects.

How about something like:
Enable the plugin in `build.sbt` on the projects (including the `root` project) you would like to test.

**Comment by fommil** [comment]
hi @kurtkopchik ... I did that initially but it didn't work, there was no `dockerComposeUp` command to use :-(

The problem as I see it is that `Command`s are project-wide whereas a `Task` could be scoped to a `Project`. So it only seems to matter to enable it on the `root`.

I raised #66 on this similar point, maybe you can show me there what I'm doing wrong and it's supported already?

**Comment by kurtkopchik** [comment]
Hi @fommil - Using the [multi-project](https://github.com/Tapad/sbt-docker-compose/blob/master/examples/multi-project/build.sbt#L7) example if I comment out `enablePlugins(DockerComposePlugin)` from the root level project but enable it on the sub-projects only I can execute `dockerComposeUp` from either of the sample sub-projects but not from the root itself which is the behavior I was describing.
```

> projects
[info] In file:/Users/kurtkopchik/Source/sbt-docker-compose/examples/multi-project/
[info] 	 * multi-project
[info] 	   sample1
[info] 	   sample2
> project multi-project
[info] Set current project to multi-project (in build file:/Users/kurtkopchik/Source/sbt-docker-compose/examples/multi-project/)
> dockerC
{invalid input}    <--- Since the plugin is not enabled on the 'root' the commands are not available.
> project sample1
[info] Set current project to sample1 (in build file:/Users/kurtkopchik/Source/sbt-docker-compose/examples/multi-project/)
> dockerComposeUp  <-- However, the dockerComposeUp commands are available on the sub-projects that have explicitly enabled it.
Building a new Docker image.
...

```

Are you seeing different behavior if you try this?

**Comment by fommil** [comment]
interesting, I didn't know `Command` worked that way. It doesn't work with `sample1/dockerComposeUp` which is (the equivalent of) what I was trying.

**Comment by kurtkopchik** [comment]
`dockerComposeUp` is a `Command` and not a `Task` which is why I believe the syntax you used isn't quite equivalent. From the interactive shell you would have to run:
```
project sample1
dockerComposeUp
```

If you need to run it from a build system (sbt on the command line) this style of syntax will work:
`sbt "project sample1" dockerComposeUp`

**Comment by fommil** [comment]
is there any chance you could make it a `Task`? `Command`s should only be as a last resort.

**Pull request closed without merging**
