### PR TITLE
Pass containerId to the test runner

### LINKED ISSUE #7: More information about containers for tests
Hi,

I would like to write tests that involve stopping/killing/relaunching containers -- I could do that by simply invoking docker as a shell command, however currently there's no reliable way to figure out which container I should interact with.

I wanted to submit a PR that passes the full information about the running services to the test runner e.g. [like this](https://github.com/sauliusvl/sbt-docker-compose/commit/c355d03eb0cd457d17f092f8bf7e2759cd8336b5), but couldn't decide on the exact syntax, i.e. should it be something like `zookeeper:id=abc123 zookeeper:tag=3.4.8` or something else.

Any suggestions / existing plans regarding this ?

### PR DESCRIPTION
**Pull request by sauliusvl**
closes #7 

are there any tests that I missed to update ?

### CODE REVIEW

**Comment by kurtkopchik** [comment]
Thanks! I wanted to get the readme and basic-with-tests example updated to reflect this new functionality as well. I can get to it later if you don't get to it first.

**Comment by sauliusvl** [comment]
The problem with the basic app is that it has a dynamically assigned port, so I can't really show off how it survives restarts. Should I make a new example ? Or fix the port ? :)

**Comment by kurtkopchik** [comment]
I was just thinking of having the current example have a test that asserts that it can get back a container id from the running instance and print it out without actually restarting the container. Just so people can see how to get back the contianerId. It'll be up to them in their own tests what they do with it.

**Comment by sauliusvl** [comment]
like this ?

**Comment by kurtkopchik** [comment]
Perfect! I'll merge the change and do an official release with the update this evening. Looking forward to more contributions in the future! 👍

**Pull request merged**
